### ISSUE TITLE
[IOS]RN 0.33 Support for defaultImageSource

### ISSUE THREAD

**Issue by ismdcf** [anvilabs/react-native-image-carousel#1]
Hi @anvilabs . Great work, This component looks awesome.  I have successfully integrated into my react project. But got one small Issue.

When passing the props to the component (renderContent) I am also passing the `defaultSource` which is a static file on the project folder . This works fine with the thumbnails but when loading the  fullscreen view it shows a black view not the defaultSource.  below is the code I have used.

**Render Method**

`                return (
                    <View>
                        <Text style={styles.sectionHeaderText}>ADDITIONAL IMAGES</Text>
                        <View style={styles.additionalImageContainer}>
                            <ImageCarousel
                                ref={(imageCarousel: ImageCarousel) => {
                                    this._imageCarousel = imageCarousel;
                                    }}
                                renderContent={this.renderImage}
                                >
                                    {this.state.imageList.map((url: string): ReactElement<any> => (
                                    <Image style={styles.thumbnailImage}
                                           key={Math.random()}
                                           source={{uri:url}}
                                           defaultSource={{uri: './images/placeholder.jpg'}}
                                           />
                                ))}
                            </ImageCarousel>
                        </View>
                    </View>
                )`

**renderImage method**

`return (
            <Image
                   style={styles.imageViewerImage}
                   resizeMode={'contain'}
                   onLoadStart={this.onImageLoadStart(i)}
                   source={{uri:this.state.imageList[i]}}
                   defaultSource={{uri: './images/placeholder.jpg'}}
                   />
        );`

Is there anything I need to do to fix it....

**Comment by binchik** [comment]
Hi, thank you for the issue. renderContent Image must have `flex: 1` to fill the fullscreen view. If that doesn't help you, please share whole component's source code in a gist.

**Comment by ismdcf** [comment]
Thanks @binchik I have set it to `flex:1`. But still It is the black screen that is presented on full screen mode before the actual image appears . My component is a bit complicated , I will create a new app with this issue and put on gist.

**Comment by ismdcf** [comment]
@binchik Also found this getting printed always (on Xcode logs ) when I open an image on full screen

`[info][tid:main][RCTImageView.m:408] Reloading image http://imagehost.com/app-images/49_68706121/359_5938951.jpeg as size {161.5, 108}`

After swiping through the images for a couple of screens the image caching resets and tries to fetch the image from the network again.

**Comment by binchik** [comment]
@ismdcf I ran your code on my machine, setting Image style to `StyleSheet.absoluteFillObject` instead of `flex: 1` does the thing, try it.

**Comment by binchik** [comment]
@ismdcf thank you, the image caching is a known issue, have no idea how to solve it at the moment. RN just always tries to reload the image on Image component size change.

If you have any guesses how to get rid of this behavior, please let me know.

**Comment by ismdcf** [comment]
Yippi, It Shows Up with `...StyleSheet.absoluteFillObject` added to the content styles, but now it does not update the image to the loaded one in fullscreen . closing full screen mode shows that the images have been loaded and consecutive opening in full screen opens the image, Thats fine rather than the black screen , Anyways I'll look into the image caching issue see if I could  find a solution :)

**Comment by ismdcf** [comment]
The Image cache reset issue was because my apps default cache size being depleted. Added the following to `Appdeligate.m` `didFinishLaunchingWithOptions` method  to increase it to 200 MB fixed the image cache resetting and now it works.

`// Set app-wide shared cache
  NSUInteger cacheSizeMemory = 200*1024*1024; // 200 MB
  NSUInteger cacheSizeDisk = 200*1024*1024; // 200 MB
  NSURLCache *sharedCache = [[NSURLCache alloc] initWithMemoryCapacity:cacheSizeMemory diskCapacity:cacheSizeDisk diskPath:@"nsurlcache"];
  [NSURLCache setSharedURLCache:sharedCache];`

**Comment by binchik** [comment]
Thank you @ismdcf, I had the same issue, will add it to the README today.
