### ISSUE TITLE
[IOS] RN 0.34 hideStatusBarOnOpen is always false when passing the onIdxChange function 

### ISSUE THREAD

**Issue by ismdcf** [anvilabs/react-native-image-carousel#2]
Hi there, I found the following issue.

When passing the **onIdxChange** function the status bar becomes visible on fullscreen mode. Explicitly setting it to false using the props **hideStatusBarOnOpen** also does not work.

Is there any work around for this issue .

**Comment by binchik** [comment]
I can't reproduce the problem you're facing, can you show the code you are using?
