### ISSUE TITLE
Is it alive? Zoom doesn't work on iOS

### ISSUE THREAD

**Issue by onrige** [anvilabs/react-native-image-carousel#7]
So I have a problem with zoom on iOS. It seems like image is updating on zooming but the result is the same.

UPD: Also I want to help with contribution if this project is still alive because it's the best image carousel at this moment for RN builded with just pure JS (hello Expo).

**Comment by simonemarinelli** [comment]
+1

**Comment by binchik** [comment]
Fixed it in 0.4.4
