### ISSUE TITLE
activeComponents usage ?

### ISSUE THREAD

**Issue by turshija** [anvilabs/react-native-image-carousel#9]
Hello,
I can't seem to find any documentation for using activeComponents property.

For example I have code like this:

```
<ImageCarousel>
  <View>
    <Image />
    <Text>Some text</Text>
    <Button>Some button</Button>
  </View>

  <View>
    <Image />
    <Text>Some text</Text>
    <Button>Some button</Button>
  </View>
</ImageCarousel>
```

When I trigger .open for that carousel, picture gets animated from `<View>` bounds instead of using `<Image>` bounds. I assume that I must somehow tell ImageCarousel to use `<Image>` instead of immediate children ? How would I do that ?

Other than that - this is literally the best gallery/carousel library for React Native ! 
Keep up the good work !

**Comment by binchik** [comment]
@turshija Hello, you'll need to keep an array of refs to your image components and pass it to ImageCarousel as `activeComponents`.

I'll clarify it in README.
